spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    mysql:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/smilebaby_local
        username: postgres
        password: postgres

    mssql:
      hikari:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=smilereader_mobile;encrypt=true;trustServerCertificate=true
        username: sa
        password: 1q2w3e4r1!
