spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  datasource:
    mysql:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/smilebaby_local
        username: root
        password: 1q2w3e4r1!

    mssql:
      hikari:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=smilereader_mobile;encrypt=true;trustServerCertificate=true
        username: sa
        password: 1q2w3e4r1!
